version: '3.8'
services:
  mysql:
    image: mysql:8.0      # Usando a versão 8 do MySQL (pode mudar para a versão que desejar)
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Senha para o usuário root
      MYSQL_DATABASE: minha_base        # Nome do banco de dados a ser criado
      MYSQL_USER: usuario                # Usuário do banco
      MYSQL_PASSWORD: senha_usuario      # Senha do usuário do banco
    ports:
      - "3306:3306"                      # Expondo a porta 3306
    volumes:
      - mysql-data:/var/lib/mysql        # Volumes para persistir os dados
    restart: always                      # Sempre reiniciar o contêiner caso caia

volumes:
  mysql-data:
    driver: local
